-- Data gathered from https://en.wikipedia.org/wiki/List_of_restaurant_chains_in_the_United_States
-- Restaurant data
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Salt Lake County', NULL, NULL, 'Cupbop', NULL, 'Utah', 'F6I 2D0');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Quezon City', NULL, NULL, 'Jollibee', NULL, 'Philippines', 'N4Z 6K4');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Honolulu', NULL, NULL, 'L&L Hawaiian Barbecue', NULL, 'Hawaii', 'L7H 7O3');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Peterborough', NULL, NULL, 'Manchu Wok', NULL, 'Ontario', 'U1H 8M0');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Denver', NULL, NULL, 'Noodles & Company', NULL, 'Colorado', 'F8U 5Z8');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Glendale', NULL, NULL, 'Panda Express', NULL, 'California', 'P5X 5X7');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Scottsdale', NULL, NULL, 'Pei Wei Asian Diner', NULL, 'Arizona', 'M0F 3P1');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('San Jose', NULL, NULL, 'Phở Hòa', NULL, 'California', 'I6W 7T7');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Rancho Santa Margarita', NULL, NULL, 'Pick Up Stix', NULL, 'California', 'K7Q 8P9');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Boston', NULL, NULL, 'Sarku Japan', NULL, 'Massachusetts', 'C8L 9D6');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Tokyo', NULL, NULL, 'Yoshinoya', NULL, 'Japan', 'U2G 3K9');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Cincinnati', NULL, NULL, 'Gold Star Chili', NULL, 'Ohio', 'O4Q 9E9');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('McDonough', NULL, NULL, 'Shane''s Rib Shack', NULL, 'Georgia', 'E1F 9V7');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Cincinnati', NULL, NULL, 'Skyline Chili', NULL, 'Ohio', 'G1H 7H9');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Chicago', NULL, NULL, 'Argo Tea', NULL, 'Illinois', 'T5L 7H9');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('East Lansing', NULL, NULL, 'Biggby Coffee', NULL, 'Michigan', 'X1A 7D3');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Portland', NULL, NULL, 'Black Rock Coffee Bar', NULL, 'Oregon', 'W1J 5E2');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Edina', NULL, NULL, 'Caribou Coffee', NULL, 'Minnesota', 'Y9Z 4H2');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Los Angeles', NULL, NULL, 'The Coffee Bean & Tea Leaf', NULL, 'California', 'V4N 7N6');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Dearborn', NULL, NULL, 'Coffee Beanery', NULL, 'Michigan', 'Z8H 5Q0');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Quincy', NULL, NULL, 'Dunkin'' Donuts', NULL, 'Massachusetts', 'H4M 8B4');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Saint Paul', NULL, NULL, 'Dunn Brothers Coffee', NULL, 'Minnesota', 'U2S 6Z2');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Grants Pass', NULL, NULL, 'Dutch Bros. Coffee', NULL, 'Oregon', 'B2N 4G2');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Long Grove', NULL, NULL, 'Gloria Jean''s Coffees', NULL, 'Illinois', 'V0U 5R2');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('New York', NULL, NULL, 'Gregorys Coffee', NULL, 'New York', 'O0F 1G2');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Louisville', NULL, NULL, 'Heine Brothers''', NULL, 'Kentucky', 'E7D 9Z0');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Chicago', NULL, NULL, 'Intelligentsia Coffee & Tea', NULL, 'Illinois', 'B2G 1Y1');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('San Luis Obispo', NULL, NULL, 'Jamba Juice', NULL, 'California', 'B2X 8T0');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Brea', NULL, NULL, 'Juice It Up!', NULL, 'California', 'S1H 7Q1');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Los Angeles', NULL, NULL, 'Orange Julius', NULL, 'California', 'F5H 5X1');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Berkeley', NULL, NULL, 'Peet''s Coffee', NULL, 'California', 'P0C 2I2');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('San Francisco', NULL, NULL, 'Philz Coffee', NULL, 'California', 'W6A 5Q8');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Atlanta', NULL, NULL, 'Planet Smoothie', NULL, 'Georgia', 'K2Q 5C8');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Los Angeles', NULL, NULL, 'Robeks', NULL, 'California', 'W7C 2X3');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Seattle', NULL, NULL, 'Seattle''s Best Coffee', NULL, 'Washington', 'X1E 4I6');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Kenner', NULL, NULL, 'Smoothie King', NULL, 'Louisiana', 'G8F 3P6');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Seattle', NULL, NULL, 'Starbucks', NULL, 'Washington', 'G1S 1T7');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Hamilton', NULL, NULL, 'Tim Hortons', NULL, 'Ontario', 'Q4H 8X3');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Destin', NULL, NULL, 'Tropical Smoothie Cafe', NULL, 'Florida', 'D5Q 0I3');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Charlotte', NULL, NULL, 'Bojangles'' Famous Chicken ''n Biscuits', NULL, 'North Carolina', 'T2F 9G7');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Bridgeview', NULL, NULL, 'Brown''s Chicken & Pasta', NULL, 'Illinois', 'D5Q 0I3');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Newton', NULL, NULL, 'Boston Market', NULL, 'Massachusetts', 'T2F 9G7');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Waco', NULL, NULL, 'Bush''s Chicken', NULL, 'Texas', 'G7R 7V6');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Birmingham', NULL, NULL, 'Chester''s International', NULL, ' Alabama', 'G3G 0F1');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Hapeville', NULL, NULL, 'Chick-fil-A', NULL, 'Georgia', 'S2T 7V4');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Benbrook', NULL, NULL, 'Chicken Express', NULL, 'Texas', 'J8M 8I4');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('San Antonio', NULL, NULL, 'Church''s Chicken', NULL, 'Texas', 'K7I 0K3');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('New Brunswick', NULL, NULL, 'Cluck-U Chicken', NULL, 'New Jersey', 'Z8A 7B8');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Guasave', NULL, NULL, 'El Pollo Loco', NULL, 'Sinaloa', 'E5Y 5M0');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('San Marcos', NULL, NULL, 'Golden Chick', NULL, 'Texas', 'M7C 0B0');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Haleyville', NULL, NULL, 'Guthrie''s', NULL, 'Alabama', 'X5E 2Z8');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Spring', NULL, NULL, 'Hartz Chicken', NULL, '	Texas', 'C1P 8D8');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('North Corbin', NULL, NULL, 'KFC', NULL, 'Kentucky', 'K6B 1D7');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Lima', NULL, NULL, 'Lee''s Famous Recipe Chicken', NULL, 'Ohio', 'R6K 4D6');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Los Angeles', NULL, NULL, 'Louisiana Famous Fried Chicken', NULL, 'California', 'F1B 5A1');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Mississauga', NULL, NULL, 'Shawarma Royale', NULL, 'Ontario', 'J0G 7P2');


-- User data
INSERT INTO USER (CITY, DAIRY, EGG, PEANUT, NAME, STATE, ZIPCODE) VALUES ('Milton', false, false, false, 'Sceptres', 'Ontario', 'S5D 6A4')